[profile.default]
libs = ["lib"]
# optimizer = true
# optimizer_runs = 2000
out = "out"
ramappings = [
  "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
  " @chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/src/",
  "@prb/math/=lib/prb-math/s"
]
src = "src"
# viaIR = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
